### ISSUE TITLE
Decrypt VaultFiles

### ISSUE THREAD

**Issue by MyLoginOnGitHub** [MyLoginOnGitHub/LaZagne#4]
Continue of https://github.com/AlessandroZ/LaZagne/issues/439.

**Comment by byehack** [comment]
as you said the `vaultfiles.py` problem is from py3 in https://github.com/AlessandroZ/LaZagne/issues/439#issuecomment-569489190 but i don't think so. 
i tried in the py2.7 but still not working!

**Comment by MyLoginOnGitHub** [comment]
Could you provide result of lazagle for python2?

**Comment by byehack** [comment]
> Could you provide result of lazagle for python2?

[lazagne_output.txt](https://github.com/MyLoginOnGitHub/LaZagne/files/4008112/lazagne_output.txt)
in `cmd admin` with -password parameter and win64-bit and py2.7-64bit

**Comment by MyLoginOnGitHub** [comment]
Some domain password has been found on lines 605-609. This is necessary password, isn't it??

_[+] Password found !!!
Username: nemo.z
Domain: Domain:target=desktop-26pg72u
**Password: XXX**
File: C:\Users\Tester\AppData\Roaming\Microsoft\Credentials\F4A4B8A854B685280B06DB2AF91CFBC4_

**Comment by byehack** [comment]
> Some domain password has been found on lines 605-609. This is necessary password, isn't it??
> 
> _[+] Password found !!! Username: nemo.z Domain: Domain:target=desktop-26pg72u **Password: XXX** File: C:\Users\Tester\AppData\Roaming\Microsoft\Credentials\F4A4B8A854B685280B06DB2AF91CFBC4_

this is another pc i was connect it before.

**Comment by byehack** [comment]
i think we should rewrite the `laZagne` project to python3.

**Comment by MyLoginOnGitHub** [comment]
REWRITE??? I think, it should to _improve_ it. But in your case lazagne does not works neinter on python2, or python3. I could not help in this case, sorry...

**Comment by byehack** [comment]
> REWRITE???

i mean we should recheck all of codes in lazagne to convert it to python 3 and fix some bugs.

**Comment by byehack** [comment]
> Some domain password has been found on lines 605-609.

i used my edited fork to recover them. with main lazagne my the app will crash and doesn't work.

**Comment by MyLoginOnGitHub** [comment]
> 
> 
> > Some domain password has been found on lines 605-609.
> 
> i used my edited fork to recover them. with main lazagne my the app will crash and doesn't work.

Even in python2?

**Comment by MyLoginOnGitHub** [comment]
> 
> 
> > REWRITE???
> 
> i mean we should recheck all of codes in lazagne to convert it to python 3 and fix some bugs.

I agree. Not **WE**, it just should to do it. I am really interested in it and plan to do it. But I think, this should be done by several (many) pull requests to original project. Not by merging single branch to lazagne/master. It is more easer for @AlessandroZ to view and check many little pull requests rather one and big. @AlessandroZ, please, correct me if I'm wrong :-)

**Comment by byehack** [comment]
> Even in python2?

no just python3

**Comment by byehack** [comment]
> I agree. Not **WE**, it just should to do it. I am really interested in it and plan to do it. But I think, this should be done by several (many) pull requests to original project. Not by merging single branch to lazagne/master. It is more easer for @AlessandroZ to view and check many little pull requests rather one and big. @AlessandroZ, please, correct me if I'm wrong :-)

yes but i will set appropriate name for commits name. and i said we create new repository not fork fom lazagne project. because  `AlessandroZ` doesn't have time to continue this project and make a support for py3

**Comment by byehack** [comment]
come to https://github.com/byehack/LaZagne to make a support for python 3

**Comment by AlessandroZ** [comment]
Hmm I'm not agree with you @byehack, the goal is not to create another fork. As @MyLoginOnGitHub 
 said, it much easier to create new little PRs adding some changes. Like that I could comment if I agree or not.

I never could merge yours (https://github.com/AlessandroZ/LaZagne/pull/441) because it's too big and some changes are not possible for me. You removed the python2 compatibility for example.

**Comment by byehack** [comment]
> Hmm

Hmm i closed this PR. i maked new fork: https://github.com/byehack/LaZagne
 if u want u can merge it with make new PR for yourself. i will not send any PR! :)
in this fork i'll try to change codes to compatibility for both python 2 & 3. and after test on both python 2&3 i will update the codes.

**Comment by MyLoginOnGitHub** [comment]
> come to https://github.com/byehack/LaZagne to make a support for python 3

As for me, I would prefere to improve the original project, sorry. Good luck :-)
Could I close this issue?

**Comment by byehack** [comment]
> Could I close this issue?

yes.
